version: "3"

services: 
  db: 
    image: postgres:13.1
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  front: 
    build: 
      context: ./front
      dockerfile: Dockerfile 
    volumes: 
      - ./front:/usr/src/app
    command: yarn start
    ports: 
      - 8000:3000
  api: 
    build: ./api
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev 
    volumes: 
      - ./api:/app
      - ./api/vendor/bundle:/app/vendor/bundle/
    environment: 
      TZ: Asia/Tokyo 
      RAILS_ENV: development 
    ports: 
      - 3000:3000 
    depends_on: 
      - db
volumes: 
  postgres-data: 
    driver: local
